---
# tasks file for nginx
- name: Ensure nginx is installed.
  apt:
     name: nginx
     state: present
     update_cache: yes 

- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Ensure nginx is started and enabled to start at boot.
  service: 
    name: nginx 
    state: started 
    enabled: yes
